
CREATE VIEW CONTACT AS SELECT CONTACT, PHONE from PUBLISHER;

CREATE OR REPLACE VIEW CONTACT AS SELECT CONTACT, PHONE FROM PUBLISHER WITH READ ONLY;

CREATE FORCE VIEW HOMEWORK13 AS SELECT COL1, COL2 FROM FIRSTATTEMPT;

DESC homework13;

CREATE VIEW REORDERINFO as SELECT isbn, title, contact, phone from books JOIN PUBLISHER USING(PUBID);                                    

UPDATE reorderinfo SET contact = 'Luana Tavares' WHERE contact = 'RENEE SMITH';

UPDATE reorderinfo SET ISBN = 0401140734 WHERE isbn = 0401140733;

DELETE FROM reorderinfo WHERE contact = 'RENEE SMITH';

ROLLBACK;

DROP VIEW reorderinfo;

